>>> import turtle
>>> s = turtle.getscreen
>>> s = turtle.getscreen()
>>> t = turtle.Turtle()
>>> t.forward(100)
>>> t.left(45)
>>> t.forward(100)
>>> t.left(45)
>>> t.forward(100)
>>> t.left(45)
>>> t.forward(100)
>>> t.left(45)
>>> t.forward(100)
>>> t.left(45)
>>> t.forward(100)
>>> t.left(45)
>>> t.forward(100)
>>> t.left(45)
>>> t.forward(100)
>>> t.left(90)
>>> t.right(90)
>>> t.left(100)
>>> t.forward(100)
>>> t.left(100)
>>> t.right(180)
>>> t.right(25)
>>> t.right(5)
>>> t.forward(100)
>>> t.undo()
>>> t.undo()
>>> t.undo()
>>> t.undo()
>>> t.undo()
>>> t,\.undo()
  File "<stdin>", line 1
    t,\.undo()
             ^
SyntaxError: unexpected character after line continuation character
>>> t.undo()
>>> t.undo()
>>> t.left(180)
>>> t.forward(100)
>>> t.right(45)
>>> t.right(90)
>>> t.forward(20)
>>> t.right(90)
>>> t.undo()
>>> t.left(90)
>>> t.forward(15)
>>> t.undo()
>>> t.forward(30)
>>> t.undo()
>>> t.forward(25)
>>> t.undo()
>>> t.forward(20)
>>> t.right(90)
>>> t.forward(30) 
>>> t.left(90)
>>> t.forward(20)
>>> t.left(90)
>>> t.forward(30)
>>> t.right(90)
>>> t.forward(30)
>>> t.right(90)
>>> t.forard(60)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Turtle' object has no attribute 'forard'
>>> t.forward(60)
>>> t.right(90)
>>> t.forward(15)
>>> t.right(90)
>>> t.forward(50)
>>> t.right(90)
>>> t.right(180)
>>> t.forward(10)
>>> t.left(90)
>>> t.forward(50)
>>> t.right(90)
>>> t.forward(30)
>>> t.forward(10)
>>> t.left(90)
>>> t.left(180)
>>> t.forward(70)
>>> 